backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: img
collections:
  - label: "Schwinger"
    name: "schwingers"
    folder: "public/data/schwingers"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            ["^[a-zA-Z0-9-_]+$", "Alphanumeric with dashes or underscores"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "News"
    name: "news"
    folder: "public/data/news"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            ["^[a-zA-Z0-9-_]+$", "Alphanumeric with dashes or underscores"],
        }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Vorstand"
    name: "vorstand"
    folder: "public/data/vorstand"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "DD-MM-YYYY",
        }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Bilder"
    name: "bilder"
    folder: "public/data/bilder"
    create: true
    format: "json"
    slug: "{{fields.slug}}"
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            ["^[a-zA-Z0-9-_]+$", "Alphanumeric with dashes or underscores"],
        }
