backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: img
collections:
  - label: "News"
    name: "news"
    folder: "public/data/news"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "MM-DD-YYYY",
          picker_utc: false;,
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            ["^[a-zA-Z0-9-_]+$", "Alphanumeric with dashes or underscores"],
        }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Vorstand"
    name: "vorstand"
    folder: "public/data/vorstand"
    create: true
    identifier_field: "title"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Role", name: "rolle", widget: "string" }
      - { label: "Adress", name: "adress", widget: "string" }
      - { label: "Place", name: "place", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: true,
        }

  - label: "Bilder"
    name: "bilder"
    folder: "public/data/bilder"
    create: true
    format: "json"
    slug: "{{fields.slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: true,
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            ["^[a-zA-Z0-9-_]+$", "Alphanumeric with dashes or underscores"],
        }
